# Generated by Django 4.2.6 on 2023-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
